apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cpu-vm-fixed
  namespace: virt-llab
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: cpu-vm-fixed
    spec:
      domain:
        cpu:
          sockets: 2
          cores: 1
          threads: 1
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: redhat
              chpasswd: { expire: False }
              ssh_pwauth: True

