apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: data1-dv
spec:
  pvc:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi
  source:
    blank: {}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: data2-dv
spec:
  pvc:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi
  source:
    blank: {}
